version: '3'
services:
    app:
        build: .
        container_name: remotelab_dev_app
        hostname: localhost
        volumes:
            - ".:/root/app"
        ports:
            - "4010:4010"
        env_file:
            - ./.env.dev
        restart: always

    db:
        container_name: remotelab_dev_db
        image: mariadb:latest
        environment:
            MARIADB_USER: sa
            MARIADB_PASSWORD: mariadbPW
            MARIADB_ROOT_PASSWORD: mariadbrootPW
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        expose:  
            - 3306
            - 33060
        env_file:
            - ./.env.dev
        restart: always
        
volumes:
    db_data:
