version: '3'
services:
    app:
        build: .
        container_name: remotelab_dev_app
        volumes:
            - ".:/root/app"
            - "app_upload:/root/app/upload"
        ports:
            - "4010:4010"
        env_file:
            - ./.env.dev
        restart: always

    db:
        container_name: remotelab_dev_db
        image: hypriot/rpi-mysql:latest
        environment:
            - ACCEPT_EULA=Ys
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        env_file:
            - ./.env.dev
        restart: always

volumes:
    db_data:
    app_upload: